"""add song

Revision ID: 0b45d4ae67b8
Revises: a1a5d4ce7500
Create Date: 2025-01-31 20:08:22.617327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b45d4ae67b8'
down_revision = 'a1a5d4ce7500'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trend_songs',
    sa.Column('cover_url', sa.String(), nullable=False),
    sa.Column('song_url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("(now() at time zone 'utc')"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_songs_id'), 'trend_songs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trend_songs_id'), table_name='trend_songs')
    op.drop_table('trend_songs')
    # ### end Alembic commands ###
