"""add user error

Revision ID: 317b20a4f1fb
Revises: cb0364922d31
Create Date: 2025-02-11 12:22:57.125938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317b20a4f1fb'
down_revision = 'cb0364922d31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'error')
    # ### end Alembic commands ###
