"""add images

Revision ID: bb00d65ac299
Revises: 0b45d4ae67b8
Create Date: 2025-02-03 13:59:16.916315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb00d65ac299'
down_revision = '0b45d4ae67b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('video_statss', sa.Column('cover_url', sa.String(), nullable=False))
    op.add_column('video_statss', sa.Column('video_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_statss', 'video_url')
    op.drop_column('video_statss', 'cover_url')
    op.alter_column('users', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
