"""update user uqconstraint

Revision ID: cdf0f107a6f7
Revises: c83f8caaccfe
Create Date: 2025-01-31 10:46:07.614968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cdf0f107a6f7'
down_revision = 'c83f8caaccfe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_externalid_appbundle', 'users', type_='unique')
    op.create_unique_constraint('uix_externalid_appbundle', 'users', ['app_id', 'nickname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_externalid_appbundle', 'users', type_='unique')
    op.create_unique_constraint('uix_externalid_appbundle', 'users', ['app_id', 'app_bundle'])
    # ### end Alembic commands ###

